### ISSUE TITLE
Details page of JBrowseR 404s

### ISSUE THREAD

**Issue by elliothershberg** [ihh/ihh.github.io#11]
When I click on the details button of it 404s (link leads to [https://ihh.github.io/publication/jbrowser/](https://ihh.github.io/publication/jbrowser/))

**Comment by ihh** [comment]
ah right, case sensitivity
should work when latest update gets pushed to github pages

**Comment by ihh** [comment]
actually i also needed to add the static site generated file in docs/publication/jbrowser (i always forget that) but it's good now

really need to figure out how to do this by CI...

**Comment by ihh** [comment]
See #12
